//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGTHAMSO
    {
        public string TENTHAMSO { get; set; }
        public string NOIDUNG { get; set; }
        public string GIATRI { get; set; }
    }
}
