//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.PHIEU_TIEPNHAN = new HashSet<PHIEU_TIEPNHAN>();
            this.PHIEU_BANXE = new HashSet<PHIEU_BANXE>();
            this.PHIEU_MUAXE = new HashSet<PHIEU_MUAXE>();
        }
    
        public int MA_KH { get; set; }
        public string TEN_KH { get; set; }
        public string CMND { get; set; }
        public string SDT { get; set; }
        public string DIACHI { get; set; }
        public Nullable<decimal> SOTIENNO { get; set; }
        public Nullable<bool> GIOITINH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_TIEPNHAN> PHIEU_TIEPNHAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_BANXE> PHIEU_BANXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_MUAXE> PHIEU_MUAXE { get; set; }
    }
}
