//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.PHIEU_BAOHANH = new HashSet<PHIEU_BAOHANH>();
            this.PHIEU_NHAPHANG = new HashSet<PHIEU_NHAPHANG>();
            this.PHIEUCHIs = new HashSet<PHIEUCHI>();
            this.PHIEU_THUTIEN = new HashSet<PHIEU_THUTIEN>();
            this.PHIEU_DICHVU = new HashSet<PHIEU_DICHVU>();
        }
    
        public int MA_NV { get; set; }
        public string HOTEN { get; set; }
        public string SDT { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> MA_NHOMNGUOIDUNG { get; set; }
    
        public virtual NHOMNGUOIDUNG NHOMNGUOIDUNG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_BAOHANH> PHIEU_BAOHANH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_NHAPHANG> PHIEU_NHAPHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUCHI> PHIEUCHIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_THUTIEN> PHIEU_THUTIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_DICHVU> PHIEU_DICHVU { get; set; }
    }
}
