//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_BANXE
    {
        public int ID_PHIEUBANXE { get; set; }
        public string MAPHIEUBAN { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public Nullable<System.DateTime> HANCHOTTHANHTOAN { get; set; }
        public Nullable<int> HANBAOHANH { get; set; }
        public string BS_XE { get; set; }
        public Nullable<decimal> TRIGIA { get; set; }
        public Nullable<decimal> SOTIENCONLAI { get; set; }
        public Nullable<int> MAKH { get; set; }
        public Nullable<int> MaNV { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual XE XE { get; set; }
    }
}
