//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHUTUNG
    {
        public int ID { get; set; }
        public string MA_PHUTUNG { get; set; }
        public string TEN_PHUTUNG { get; set; }
        public string MA_HIEUXE { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
        public Nullable<decimal> DONGIAXUAT { get; set; }
        public string TG_BAOHANH { get; set; }
    }
}
