//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHUTUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHUTUNG()
        {
            this.CHITIET_PHIEUBH = new HashSet<CHITIET_PHIEUBH>();
            this.CHITIET_PHIEUDV = new HashSet<CHITIET_PHIEUDV>();
            this.CHITIET_PHIEUNH = new HashSet<CHITIET_PHIEUNH>();
            this.CHITIET_PHIEUDATHANG = new HashSet<CHITIET_PHIEUDATHANG>();
            this.CHITIET_PHIEUBANLE = new HashSet<CHITIET_PHIEUBANLE>();
        }
    
        public int MA_PHUTUNG { get; set; }
        public string TEN_PHUTUNG { get; set; }
        public string MA_HIEUXE { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
        public Nullable<decimal> DONGIAXUAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_PHIEUBH> CHITIET_PHIEUBH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_PHIEUDV> CHITIET_PHIEUDV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_PHIEUNH> CHITIET_PHIEUNH { get; set; }
        public virtual HIEUXE HIEUXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_PHIEUDATHANG> CHITIET_PHIEUDATHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_PHIEUBANLE> CHITIET_PHIEUBANLE { get; set; }
    }
}
