//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XE()
        {
            this.PHIEU_TIEPNHAN = new HashSet<PHIEU_TIEPNHAN>();
            this.PHIEUBANXEs = new HashSet<PHIEUBANXE>();
        }
    
        public string BS_XE { get; set; }
        public Nullable<int> MA_KH { get; set; }
        public Nullable<System.DateTime> NGAY_TIEPNHAN { get; set; }
        public string HIEU_XE { get; set; }
        public string TINH_TRANG { get; set; }
        public Nullable<bool> HINHTHUC { get; set; }
        public string SO_MAY { get; set; }
        public string SO_KHUNG { get; set; }
        public string DOI_XE { get; set; }
        public Nullable<int> SO_KM { get; set; }
    
        public virtual HIEUXE HIEUXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_TIEPNHAN> PHIEU_TIEPNHAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUBANXE> PHIEUBANXEs { get; set; }
    }
}
